### ISSUE TITLE
Integrating with existing flask app and uwsgi.

### ISSUE THREAD

**Issue by homer6** [kennethreitz/flask-sockets#12]
I'm having a bit of an issue using flask-sockets in the context of an existing flask app. 

Any chance you could point me in the right direction? I've create a SO post for it:

http://stackoverflow.com/questions/20910616/how-to-integrate-flask-and-flask-sockets-into-a-single-app-running-under-uwsgi

Thanks in advance...

**Comment by kennethreitz** [comment]
That would be great!
