### ISSUE TITLE
Is it possible to run a flask-sockets server in a thread?

### ISSUE THREAD

**Issue by nickponline** [kennethreitz/flask-sockets#13]
I currently run a flask server in a thread using:

app = flask.Flask(__name__)
dispatcher = wsgiserver.WSGIPathInfoDispatcher({'/': app})
server = wsgiserver.CherryPyWSGIServer(('0.0.0.0', 8000), dispatcher)
server_thread = threading.Thread(target=server.start)
server_thread.daemon = True
server_thread.start()

I would like to add a socket route to this server and continue to run it it a thread instead of with gunicorn? Is this possible?

**Comment by kennethreitz** [comment]
Not that I know of.
