### ISSUE TITLE
 WebSocketError if I don't use try, except

### ISSUE THREAD

**Issue by mmcclellan** [kennethreitz/flask-sockets#17]
If I change the example code to this:

    while True:
        try:
            message = ws.receive()
            ws.send("Your message was: %r" % message)
        except:
            break

All works well. Otherwise I get WebSocketErrors when the client disconnects. Not sure if others have experienced this.

**Comment by kennethreitz** [comment]
It's best to do `while not ws.closed`.

**Comment by josephernest** [comment]
@kennethreitz  `while not ws.closed` isn't enough in some situations. `try: ... except WebSocketError:` still helps.
