### ISSUE TITLE
Using sockets with route pattern

### ISSUE THREAD

**Issue by issackelly** [kennethreitz/flask-sockets#23]
I've got the following code, and it will open and immediately close the websocket connection.

    @sockets.route('/sockets/<channel>')
    def echo_socket(ws):
        while True:
            message = ws.receive()
            ws.send(message)

Not quite sure if this is a feature request or a bug, but I think that WS routes should be able to accept flask route patterns.

**Comment by philipn** [comment]
In case you missed it, there's a PR over here to allow this behavior https://github.com/kennethreitz/flask-sockets/pull/18

**Comment by issackelly** [comment]
Thanks!

**Comment by kennethreitz** [comment]
This is now supported!

**Comment by issackelly** [comment]
:+1:
