### ISSUE TITLE
AttributeError: 'WebSocket' object has no attribute 'socket'

### ISSUE THREAD

**Issue by no13bus** [kennethreitz/flask-sockets#24]
my flask version is 0.10.
When I type `gunicorn -k flask_sockets.worker chat:app`, there is an error:
`AttributeError: 'WebSocket' object has no attribute 'socket'`
why?

**Comment by syntonym** [comment]
@no13bus Can you show the code that throws that error?

**Comment by jcipriano** [comment]
I just ran into this as well.

This code is from:
https://github.com/heroku-examples/python-websockets-chat/blob/master/chat.py

```python
@sockets.route('/receive')
def outbox(ws):
    """Sends outgoing chat messages, via `ChatBackend`."""
    chats.register(ws)

    while ws.socket is not None:
        # Context switch while `ChatBackend.start` is running in the background.
        gevent.sleep()
```

**Comment by jcipriano** [comment]
The issue does not occur if you downgrade gevent-websocket to version 0.3.6 as discussed here:

https://bitbucket.org/Jeffrey/gevent-websocket/issue/50/errors-with-version-092-and-flask-sockets

However, the last solution provided in that discussion to work with the recent version of gevent-websocket did not work for me.

Hope this helps someone.

**Comment by syntonym** [comment]
It looks like the websocket api changed. An websocket object has no longer a `socket` attribute, but a boolean `closed` that should indicate if the websocket is open or not. 

@jcipriano What happens if you use the solution with `with not ws.closed:`?

**Comment by versae** [comment]
Thanks @syntonym, that worked for me.

**Comment by ondrae** [comment]
@syntonym `while not ws.closed:`

**Comment by syntonym** [comment]
@ondrae You are of course correct. Thanks!

**Comment by kennethreitz** [comment]
`while not ws.closed` is indeed proper. I've updated the code in the [example chat app repository](https://github.com/heroku-examples/python-websockets-chat) to feature the new usage. Sorry for the confusion!
