### ISSUE TITLE
Question: how to make ws socket receive non-blocking ?

### ISSUE THREAD

**Issue by StudentForever** [kennethreitz/flask-sockets#30]
Hi

I am a python newbie, I am wondering what are good options for making the socket receive method non-blocking on the serve-side ?

Thanks

**Comment by kennethreitz** [comment]
This project uses gevent, so all blocking calls are automatically added to an event loop, and behave asynchronously.

**Comment by kennethreitz** [comment]
p.s. @StudentForever, your username is fantastic. :)

**Comment by StudentForever** [comment]
Hi

I attached the python server and Js client code.

I have added my questions as inline comments in the code but here they are
1. ws.receive() seems to be blocking, I don't see the print statement after the ws.receive() statement
2. when I close the socket from JavaScript client, I don't think the connection is getting closed. I might be doing something dumb but cannot figure it out yet.

Thanks a lot for your time.


[example.zip](https://github.com/kennethreitz/flask-sockets/files/238892/example.zip)
