### ISSUE TITLE
Is flask-sockets supports broadcasting?

### ISSUE THREAD

**Issue by rajasimon** [kennethreitz/flask-sockets#40]
All web sockets connected to the same endpoint but `ws.send(message)` will receive by only one client which is initiated `socket.send('message')`

**Comment by mariotti** [comment]
If I am not wrong WS are peer to peer by definition. Meaning you can open as many connections as you want and your server can support, but it is not exactly "broadcasting".

If you can expand the question with examples maybe it becomes more clear.

**Comment by oblalex** [comment]
Will it be OK for you to keep a pool of open connections and to send messages to clients kept in it?

**Comment by rajasimon** [comment]
@oblalex  yes I'm thinking the same.

**Comment by rajasimon** [comment]
In the mean time I found this very helpful. I have modified lot of code to adapt my need. I wish flask-sockets will have these feature inbuilt. 

Ref: https://github.com/heroku-examples/python-websockets-chat
