### ISSUE TITLE
is multi-worker supported when deploy with gunicorn ?

### ISSUE THREAD

**Issue by hustcc** [kennethreitz/flask-sockets#41]
deploy use below: 

```sh
gunicorn -k flask_sockets.worker -w 4 hello:app
```

**Comment by oblalex** [comment]
@hustcc Yes.

Personally I use it like this: [Procfile](https://github.com/IL2HorusTeam/demo-services/blob/master/Procfile). Works fine.

Does this answer your question?

**Comment by hustcc** [comment]
Year, sure.
