### ISSUE TITLE
Issue with blueprints

### ISSUE THREAD

**Issue by LennartKloppenburg** [kennethreitz/flask-sockets#47]
Hey,

Thanks a lot for the beautiful extension. I'm having some trouble with including this for Blueprints. I created an[ issue on Stackoverflow](http://stackoverflow.com/questions/43803927/python-flask-sockets-not-working-within-blueprints) before, I hope it's alright... Could you help me along a little bit?
Thanks a lot in advance!

**Comment by tkrajca** [comment]
Hi @LennartKloppenburg, I answered your question on Stackoverflow, closing this one for now.
