### ISSUE TITLE
The example code gives me an error?

### ISSUE THREAD

**Issue by kramer65** [kennethreitz/flask-sockets#8]
I'm trying to use Flask-Sockets with the example code:
```
sockets = Sockets(app)
    
@sockets.route('/echo')
def echo_socket(ws):
    while True:
        message = ws.receive()
        ws.send(message)
```
Unfortunately it gives me an error saying:

```
    File "/Library/Python/2.7/site-packages/Flask-0.10-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
    File "/Library/Python/2.7/site-packages/flask_sockets.py", line 37, in __call__
    environment = environ['wsgi.websocket']
    KeyError: 'wsgi.websocket'
```
Anybody any ideas what I'm doing wrong? All tips are welcome!

**Comment by jasdevsidhu** [comment]
Guys I am getting this error , help me out

/home/www/flask_project# gunicorn -k flask_sockets.worker main2:app

Error: class uri 'flask_sockets.worker' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 140, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named flask_sockets
]

This is my main2.py

from gevent import monkey;monkey.patch_all()
from flask import Flask,render_template, url_for, request, redirect, flash,jsonify,session,Markup
from socketio import socketio_manage
from socketio.namespace import BaseNamespace
from socketio.server import SocketIOServer

app=Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'

class ChatNamespace(BaseNamespace):
    def recv_connect(self):
        print "successfully connected"
        self.emit('show_result','successfully connect')
    def on_receive_message(self,msg):
        print "message is "+msg["data"]
        self.emit('show_result2',msg["data"])
@app.route('/')
def index():
    #print "in the function"
    return render_template('index.html')

@app.route("/socket.io/<path:path>")
def run_socketio(path):
    socketio_manage(request.environ, {'/test': ChatNamespace})
    return 'ok'

if __name__=='__main__':
    #app.run(debug=True, port=80, host='0.0.0.0')
    app.debug=True
    #app.run()
    SocketIOServer(('0.0.0.0', 5000), app,resource="socket.io").serve_forever()
    print "successfull listen to socket"

**Comment by kennethreitz** [comment]
@jasdevsidhu you must install the module in order to use it :)
